import type { Metadata } from "next";
import { dark } from "@clerk/themes";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";

import { Toaster } from "sonner";

import "./globals.css";
import ReactQueryProviders from "@/provider/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Gamehub",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider appearance={{ baseTheme: dark }}>
			<html lang="en">
				<body className={inter.className}>
					<ReactQueryProviders>
						<ThemeProvider
							attribute="class"
							forcedTheme="dark"
							storageKey="gamehub-theme"
						>
							<Toaster theme="light" position="bottom-center" />
							{children}
						</ThemeProvider>
					</ReactQueryProviders>
				</body>
			</html>
		</ClerkProvider>
	);
}
